# Generated by Django 4.2.7 on 2025-05-17 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DINRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.IntegerField(blank=True, null=True)),
                ('end_range', models.IntegerField(blank=True, null=True)),
                ('input_csv', models.FileField(blank=True, null=True, upload_to='inputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('output_csv', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('din_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_status', to='din_app.dinrequest')),
            ],
        ),
    ]
