# Generated by Django 4.2.7 on 2025-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('din_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinrequest',
            name='din_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
